# Starter pipeline

trigger:
 branches:
   include:
     - main

pool:
  mypool

stages:
  - stage: terraformsetup
    jobs:
      - job: terraformsetup
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'



