# Starter pipeline

trigger:
 branches:
   include:
     - main

pool:
  mypool

stages:
  - stage: terraformsetup
    jobs:
      - job: terraformsetup
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              sudo apt-get update
              sudo apt-get install -y unzip
            displayName: Install unzip



